### ISSUE TITLE
Rendering partial for new question errors out 

### ISSUE THREAD

**Issue by freakinrican1** [omahacodeschool/nonprofitam-infrastructure-checklist#10]
We are currently experiencing some model inception. We are trying to render a partial for question#new on-click within the checklist#new view. Ajax is getting to the partial and then error-ing out because 'builder' method doesn't exit. As we are inserting the partial within a builder block, we are unsure why its not being recognized.

**Comment by sumeetjain** [comment]
It's easier to discuss things like this if there's code to look at and comment on. Can you start this conversation within the context of some code? https://github.com/omahacodeschool/nonprofitam-infrastructure-checklist/pull/9/files
