### ISSUE TITLE
Answers hash gets clobbered with each new checklist's response.

### ISSUE THREAD

**Issue by sumeetjain** [omahacodeschool/nonprofitam-infrastructure-checklist#12]
Not sure if this has been fixed locally or not, but I found this to be a problem:
1. I do X checklist. Answer some questions (A, B, and C). Submit.
2. Now my Response's `answers_hash` has A, B, C.
3. I do Y checklist. Answer some questions (D, M, P, Q). Submit.
4. Problem
   - **Expected:** `answers_hash` has A, B, C, D, M, P, Q.
   - **Actual:** `answers_hash` has D, M, P, Q

**Comment by freakinrican1** [comment]
I believe this bug has been resolved. I do not know the industry standard for reporting a bugs resolution. 
The hash needed to be merged when params were updated. Fixed in the response controller#update on line 21
